// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1-0.20260518235555-9bb79e703422 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ClientJWTScopes clientJWTContextKey = "ClientJWT.Scopes"
	UserJWTScopes   userJWTContextKey   = "UserJWT.Scopes"
)

// Defines values for RevokeRequestTokenTypeHint.
const (
	RevokeRequestTokenTypeHintAccessToken  RevokeRequestTokenTypeHint = "access_token"
	RevokeRequestTokenTypeHintRefreshToken RevokeRequestTokenTypeHint = "refresh_token"
)

// Valid indicates whether the value is a known member of the RevokeRequestTokenTypeHint enum.
func (e RevokeRequestTokenTypeHint) Valid() bool {
	switch e {
	case RevokeRequestTokenTypeHintAccessToken:
		return true
	case RevokeRequestTokenTypeHintRefreshToken:
		return true
	default:
		return false
	}
}

// Defines values for TokenRequestGrantType.
const (
	TokenRequestGrantTypeAuthorizationCode TokenRequestGrantType = "authorization_code"
	TokenRequestGrantTypeClientCredentials TokenRequestGrantType = "client_credentials"
	TokenRequestGrantTypeRefreshToken      TokenRequestGrantType = "refresh_token"
)

// Valid indicates whether the value is a known member of the TokenRequestGrantType enum.
func (e TokenRequestGrantType) Valid() bool {
	switch e {
	case TokenRequestGrantTypeAuthorizationCode:
		return true
	case TokenRequestGrantTypeClientCredentials:
		return true
	case TokenRequestGrantTypeRefreshToken:
		return true
	default:
		return false
	}
}

// Defines values for AuthorizeParamsResponseType.
const (
	Code AuthorizeParamsResponseType = "code"
)

// Valid indicates whether the value is a known member of the AuthorizeParamsResponseType enum.
func (e AuthorizeParamsResponseType) Valid() bool {
	switch e {
	case Code:
		return true
	default:
		return false
	}
}

// Defines values for AuthorizeParamsCodeChallengeMethod.
const (
	S256 AuthorizeParamsCodeChallengeMethod = "S256"
)

// Valid indicates whether the value is a known member of the AuthorizeParamsCodeChallengeMethod enum.
func (e AuthorizeParamsCodeChallengeMethod) Valid() bool {
	switch e {
	case S256:
		return true
	default:
		return false
	}
}

// AuthenticatorAssertionResponse defines model for AuthenticatorAssertionResponse.
type AuthenticatorAssertionResponse struct {
	// AuthenticatorData Base64url-encoded authenticator data
	AuthenticatorData string `json:"authenticatorData"`

	// ClientDataJSON Base64url-encoded JSON
	ClientDataJSON string `json:"clientDataJSON"`

	// Signature Base64url-encoded signature
	Signature string `json:"signature"`

	// UserHandle Base64url-encoded user handle
	UserHandle *string `json:"userHandle,omitempty"`
}

// AuthenticatorAttestationResponse defines model for AuthenticatorAttestationResponse.
type AuthenticatorAttestationResponse struct {
	// AttestationObject Base64url-encoded CBOR attestation object
	AttestationObject string `json:"attestationObject"`

	// AuthenticatorData Base64url-encoded authenticator data
	AuthenticatorData *string `json:"authenticatorData,omitempty"`

	// ClientDataJSON Base64url-encoded JSON
	ClientDataJSON string    `json:"clientDataJSON"`
	Transports     *[]string `json:"transports,omitempty"`
}

// AuthenticatorSelection defines model for AuthenticatorSelection.
type AuthenticatorSelection struct {
	AuthenticatorAttachment *string `json:"authenticatorAttachment,omitempty"`
	RequireResidentKey      *bool   `json:"requireResidentKey,omitempty"`
	ResidentKey             *string `json:"residentKey,omitempty"`
	UserVerification        *string `json:"userVerification,omitempty"`
}

// CredentialAssertionOptionsResponse defines model for CredentialAssertionOptionsResponse.
type CredentialAssertionOptionsResponse struct {
	Mediation *string                           `json:"mediation,omitempty"`
	PublicKey PublicKeyCredentialRequestOptions `json:"publicKey"`
}

// CredentialAssertionResponseBody defines model for CredentialAssertionResponseBody.
type CredentialAssertionResponseBody struct {
	AuthenticatorAttachment *string                 `json:"authenticatorAttachment,omitempty"`
	ClientExtensionResults  *map[string]interface{} `json:"clientExtensionResults,omitempty"`
	Id                      string                  `json:"id"`

	// RawId Base64url-encoded credential ID
	RawId    string                         `json:"rawId"`
	Response AuthenticatorAssertionResponse `json:"response"`
	Type     string                         `json:"type"`
}

// CredentialCreationOptionsResponse defines model for CredentialCreationOptionsResponse.
type CredentialCreationOptionsResponse struct {
	Mediation *string                            `json:"mediation,omitempty"`
	PublicKey PublicKeyCredentialCreationOptions `json:"publicKey"`
}

// CredentialCreationResponseBody defines model for CredentialCreationResponseBody.
type CredentialCreationResponseBody struct {
	AuthenticatorAttachment *string                 `json:"authenticatorAttachment,omitempty"`
	ClientExtensionResults  *map[string]interface{} `json:"clientExtensionResults,omitempty"`
	Id                      string                  `json:"id"`

	// RawId Base64url-encoded credential ID
	RawId    string                           `json:"rawId"`
	Response AuthenticatorAttestationResponse `json:"response"`
	Type     string                           `json:"type"`
}

// CredentialDescriptor defines model for CredentialDescriptor.
type CredentialDescriptor struct {
	// Id Base64url-encoded credential ID
	Id         string    `json:"id"`
	Transports *[]string `json:"transports,omitempty"`
	Type       string    `json:"type"`
}

// CredentialParameter defines model for CredentialParameter.
type CredentialParameter struct {
	// Alg COSE algorithm identifier (-7 = ES256, -257 = RS256)
	Alg  int    `json:"alg"`
	Type string `json:"type"`
}

// IntrospectRequest defines model for IntrospectRequest.
type IntrospectRequest struct {
	Token string `json:"token"`
}

// IntrospectResponse defines model for IntrospectResponse.
type IntrospectResponse struct {
	Active    bool    `json:"active"`
	Aud       *string `json:"aud,omitempty"`
	ClientId  *string `json:"client_id,omitempty"`
	Exp       *int64  `json:"exp,omitempty"`
	Iat       *int64  `json:"iat,omitempty"`
	Scope     *string `json:"scope,omitempty"`
	Sub       *string `json:"sub,omitempty"`
	TokenType *string `json:"token_type,omitempty"`
}

// JWK defines model for JWK.
type JWK struct {
	Alg string `json:"alg"`

	// E RSA exponent (base64url)
	E   string `json:"e"`
	Kid string `json:"kid"`
	Kty string `json:"kty"`

	// N RSA modulus (base64url)
	N   string `json:"n"`
	Use string `json:"use"`
}

// JWKS defines model for JWKS.
type JWKS struct {
	Keys []JWK `json:"keys"`
}

// OTPRequest defines model for OTPRequest.
type OTPRequest struct {
	Email openapi_types.Email `json:"email"`
}

// OTPVerifyRequest defines model for OTPVerifyRequest.
type OTPVerifyRequest struct {
	// Code The OTP code delivered to the user
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
}

// PasskeyLoginBeginRequest defines model for PasskeyLoginBeginRequest.
type PasskeyLoginBeginRequest struct {
	// ClientId OAuth client ID of the BFF/confidential client initiating the login
	ClientId string              `json:"client_id"`
	Email    openapi_types.Email `json:"email"`
}

// PasskeyRegisteredResponse defines model for PasskeyRegisteredResponse.
type PasskeyRegisteredResponse struct {
	CreatedAt time.Time `json:"created_at"`

	// CredentialId Base64url-encoded credential ID
	CredentialId string `json:"credential_id"`
}

// Problem RFC 7807 Problem+JSON
type Problem struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// PublicKeyCredentialCreationOptions defines model for PublicKeyCredentialCreationOptions.
type PublicKeyCredentialCreationOptions struct {
	Attestation            *string                 `json:"attestation,omitempty"`
	AuthenticatorSelection *AuthenticatorSelection `json:"authenticatorSelection,omitempty"`

	// Challenge Base64url-encoded challenge
	Challenge          string                  `json:"challenge"`
	ExcludeCredentials *[]CredentialDescriptor `json:"excludeCredentials,omitempty"`
	Extensions         *map[string]interface{} `json:"extensions,omitempty"`
	PubKeyCredParams   *[]CredentialParameter  `json:"pubKeyCredParams,omitempty"`
	Rp                 RelyingPartyEntity      `json:"rp"`
	Timeout            *int                    `json:"timeout,omitempty"`
	User               UserEntity              `json:"user"`
}

// PublicKeyCredentialRequestOptions defines model for PublicKeyCredentialRequestOptions.
type PublicKeyCredentialRequestOptions struct {
	AllowCredentials *[]CredentialDescriptor `json:"allowCredentials,omitempty"`

	// Challenge Base64url-encoded challenge
	Challenge        string                  `json:"challenge"`
	Extensions       *map[string]interface{} `json:"extensions,omitempty"`
	RpId             *string                 `json:"rpId,omitempty"`
	Timeout          *int                    `json:"timeout,omitempty"`
	UserVerification *string                 `json:"userVerification,omitempty"`
}

// RegisteredClient Public view of an OAuth client — secret is never included
type RegisteredClient struct {
	AllowedScopes []string `json:"allowed_scopes"`
	ClientId      string   `json:"client_id"`
	Name          string   `json:"name"`
}

// RelyingPartyEntity defines model for RelyingPartyEntity.
type RelyingPartyEntity struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// RevokeRequest defines model for RevokeRequest.
type RevokeRequest struct {
	// ClientId Client ID — alternative to HTTP Basic authentication (RFC 7009 §2.1)
	ClientId *string `json:"client_id,omitempty"`

	// ClientSecret Client secret — alternative to HTTP Basic authentication (RFC 7009 §2.1)
	ClientSecret  *string                     `json:"client_secret,omitempty"`
	Token         string                      `json:"token"`
	TokenTypeHint *RevokeRequestTokenTypeHint `json:"token_type_hint,omitempty"`
}

// RevokeRequestTokenTypeHint defines model for RevokeRequest.TokenTypeHint.
type RevokeRequestTokenTypeHint string

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`

	// Code Required for authorization_code grant
	Code *string `json:"code,omitempty"`

	// CodeVerifier PKCE code verifier — required when code_challenge was used in the authorization request (RFC 7636)
	CodeVerifier *string               `json:"code_verifier,omitempty"`
	GrantType    TokenRequestGrantType `json:"grant_type"`

	// RedirectUri Required for authorization_code grant
	RedirectUri *string `json:"redirect_uri,omitempty"`

	// RefreshToken Required for refresh_token grant
	RefreshToken *string `json:"refresh_token,omitempty"`
	Scope        *string `json:"scope,omitempty"`
}

// TokenRequestGrantType defines model for TokenRequest.GrantType.
type TokenRequestGrantType string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Seconds until token expires
	ExpiresIn    int     `json:"expires_in"`
	RefreshToken *string `json:"refresh_token,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	TokenType    string  `json:"token_type"`
}

// UserEntity defines model for UserEntity.
type UserEntity struct {
	DisplayName string `json:"displayName"`

	// Id Base64url-encoded user handle
	Id   string `json:"id"`
	Name string `json:"name"`
}

// ValidateRequest defines model for ValidateRequest.
type ValidateRequest struct {
	Token string `json:"token"`
}

// ValidateResponse defines model for ValidateResponse.
type ValidateResponse struct {
	// Error Present when valid is false
	Error  *string   `json:"error,omitempty"`
	Scopes *[]string `json:"scopes,omitempty"`

	// Sub Token subject (user ID or service ID)
	Sub   *string `json:"sub,omitempty"`
	Valid bool    `json:"valid"`
}

// BadRequest RFC 7807 Problem+JSON
type BadRequest = Problem

// Forbidden RFC 7807 Problem+JSON
type Forbidden = Problem

// NotFound RFC 7807 Problem+JSON
type NotFound = Problem

// Unauthorized RFC 7807 Problem+JSON
type Unauthorized = Problem

// clientJWTContextKey is the context key for ClientJWT security scheme
type clientJWTContextKey string

// userJWTContextKey is the context key for UserJWT security scheme
type userJWTContextKey string

// AuthorizeParams defines parameters for Authorize.
type AuthorizeParams struct {
	ResponseType        AuthorizeParamsResponseType         `form:"response_type" json:"response_type"`
	ClientId            string                              `form:"client_id" json:"client_id"`
	RedirectUri         string                              `form:"redirect_uri" json:"redirect_uri"`
	Scope               *string                             `form:"scope,omitempty" json:"scope,omitempty"`
	State               *string                             `form:"state,omitempty" json:"state,omitempty"`
	CodeChallenge       *string                             `form:"code_challenge,omitempty" json:"code_challenge,omitempty"`
	CodeChallengeMethod *AuthorizeParamsCodeChallengeMethod `form:"code_challenge_method,omitempty" json:"code_challenge_method,omitempty"`
}

// AuthorizeParamsResponseType defines parameters for Authorize.
type AuthorizeParamsResponseType string

// AuthorizeParamsCodeChallengeMethod defines parameters for Authorize.
type AuthorizeParamsCodeChallengeMethod string

// IntrospectTokenJSONRequestBody defines body for IntrospectToken for application/json ContentType.
type IntrospectTokenJSONRequestBody = IntrospectRequest

// RevokeTokenJSONRequestBody defines body for RevokeToken for application/json ContentType.
type RevokeTokenJSONRequestBody = RevokeRequest

// IssueTokenJSONRequestBody defines body for IssueToken for application/json ContentType.
type IssueTokenJSONRequestBody = TokenRequest

// RequestOTPJSONRequestBody defines body for RequestOTP for application/json ContentType.
type RequestOTPJSONRequestBody = OTPRequest

// VerifyOTPJSONRequestBody defines body for VerifyOTP for application/json ContentType.
type VerifyOTPJSONRequestBody = OTPVerifyRequest

// BeginPasskeyLoginJSONRequestBody defines body for BeginPasskeyLogin for application/json ContentType.
type BeginPasskeyLoginJSONRequestBody = PasskeyLoginBeginRequest

// CompletePasskeyLoginJSONRequestBody defines body for CompletePasskeyLogin for application/json ContentType.
type CompletePasskeyLoginJSONRequestBody = CredentialAssertionResponseBody

// CompletePasskeyRegistrationJSONRequestBody defines body for CompletePasskeyRegistration for application/json ContentType.
type CompletePasskeyRegistrationJSONRequestBody = CredentialCreationResponseBody

// ValidateTokenJSONRequestBody defines body for ValidateToken for application/json ContentType.
type ValidateTokenJSONRequestBody = ValidateRequest
