// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1-0.20260518235555-9bb79e703422 DO NOT EDIT.
package user

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ServiceJWTScopes serviceJWTContextKey = "ServiceJWT.Scopes"
	UserJWTScopes    userJWTContextKey    = "UserJWT.Scopes"
)

// Defines values for CredentialsResponseAuthMethods.
const (
	CredentialsResponseAuthMethodsApple    CredentialsResponseAuthMethods = "apple"
	CredentialsResponseAuthMethodsGoogle   CredentialsResponseAuthMethods = "google"
	CredentialsResponseAuthMethodsPassword CredentialsResponseAuthMethods = "password"
)

// Valid indicates whether the value is a known member of the CredentialsResponseAuthMethods enum.
func (e CredentialsResponseAuthMethods) Valid() bool {
	switch e {
	case CredentialsResponseAuthMethodsApple:
		return true
	case CredentialsResponseAuthMethodsGoogle:
		return true
	case CredentialsResponseAuthMethodsPassword:
		return true
	default:
		return false
	}
}

// Defines values for UserExistsResponseAuthMethods.
const (
	UserExistsResponseAuthMethodsApple    UserExistsResponseAuthMethods = "apple"
	UserExistsResponseAuthMethodsGoogle   UserExistsResponseAuthMethods = "google"
	UserExistsResponseAuthMethodsPassword UserExistsResponseAuthMethods = "password"
)

// Valid indicates whether the value is a known member of the UserExistsResponseAuthMethods enum.
func (e UserExistsResponseAuthMethods) Valid() bool {
	switch e {
	case UserExistsResponseAuthMethodsApple:
		return true
	case UserExistsResponseAuthMethodsGoogle:
		return true
	case UserExistsResponseAuthMethodsPassword:
		return true
	default:
		return false
	}
}

// Address defines model for Address.
type Address struct {
	AddressId string `json:"address_id"`

	// Alias Friendly label (e.g. "Home", "Work")
	Alias *string `json:"alias,omitempty"`
	City  string  `json:"city"`

	// Country ISO 3166-1 alpha-2 country code (e.g. "US")
	Country   string  `json:"country"`
	IsDefault bool    `json:"is_default"`
	Line1     string  `json:"line1"`
	Line2     *string `json:"line2,omitempty"`
	State     string  `json:"state"`
	ZipCode   string  `json:"zip_code"`
}

// AddressInput defines model for AddressInput.
type AddressInput struct {
	Alias *string `json:"alias,omitempty"`
	City  string  `json:"city"`

	// Country ISO 3166-1 alpha-2 country code (e.g. "US")
	Country   string  `json:"country"`
	IsDefault *bool   `json:"is_default,omitempty"`
	Line1     string  `json:"line1"`
	Line2     *string `json:"line2,omitempty"`
	State     string  `json:"state"`
	ZipCode   string  `json:"zip_code"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	AvatarUrl     *string             `json:"avatar_url,omitempty"`
	Email         openapi_types.Email `json:"email"`
	FirstName     string              `json:"first_name"`
	LastName      string              `json:"last_name"`
	MiddleInitial *string             `json:"middle_initial,omitempty"`
	Phone         *string             `json:"phone,omitempty"`
}

// CredentialsResponse Internal-only credential fields for auth-api login verification
type CredentialsResponse struct {
	// AuthMethods Authentication methods registered for this account
	AuthMethods   []CredentialsResponseAuthMethods `json:"auth_methods"`
	EmailVerified bool                             `json:"email_verified"`

	// PasswordHash bcrypt hash; empty for OAuth-only accounts
	PasswordHash *string `json:"password_hash,omitempty"`
	UserId       string  `json:"user_id"`
}

// CredentialsResponseAuthMethods defines model for CredentialsResponse.AuthMethods.
type CredentialsResponseAuthMethods string

// PasskeyCredential WebAuthn credential record (ADR 002 §7) — public key bytes only
type PasskeyCredential struct {
	// Aaguid base64-encoded authenticator AAGUID
	Aaguid         *string   `json:"aaguid,omitempty"`
	BackupEligible bool      `json:"backup_eligible"`
	BackupState    bool      `json:"backup_state"`
	CreatedAt      time.Time `json:"created_at"`

	// CredentialId base64url-encoded WebAuthn credential ID; natural unique key
	CredentialId string     `json:"credential_id"`
	LastUsedAt   *time.Time `json:"last_used_at,omitempty"`

	// PublicKey base64-encoded COSE public key bytes
	PublicKey  string    `json:"public_key"`
	SignCount  int64     `json:"sign_count"`
	Transports *[]string `json:"transports,omitempty"`
}

// PaymentMethod Stored payment method reference — no raw card data, metadata only
type PaymentMethod struct {
	// Brand Card network (e.g. "visa", "mastercard", "amex")
	Brand       string `json:"brand"`
	ExpiryMonth int    `json:"expiry_month"`
	ExpiryYear  int    `json:"expiry_year"`
	IsDefault   bool   `json:"is_default"`

	// Last4 Last 4 digits of the card number
	Last4     string `json:"last4"`
	PaymentId string `json:"payment_id"`

	// Provider Payment processor (e.g. "stripe")
	Provider string `json:"provider"`
}

// PaymentMethodInput Payment processor token submitted by the client to save a payment method
type PaymentMethodInput struct {
	IsDefault *bool `json:"is_default,omitempty"`

	// Provider Payment processor (e.g. "stripe")
	Provider string `json:"provider"`

	// Token Payment processor token (e.g. Stripe payment method ID "pm_xxx")
	Token string `json:"token"`
}

// Preferences defines model for Preferences.
type Preferences struct {
	// Communication Notification channel opt-ins keyed by channel name (e.g. email, sms, push)
	Communication *map[string]bool `json:"communication,omitempty"`

	// Language BCP 47 language tag (e.g. "en-US")
	Language *string `json:"language,omitempty"`

	// Marketing Marketing preferences keyed by attribute (e.g. frequency, channel)
	Marketing *map[string]string `json:"marketing,omitempty"`

	// Timezone IANA timezone (e.g. "America/New_York")
	Timezone *string `json:"timezone,omitempty"`
}

// ProblemDetail RFC 7807 Problem+JSON error body
type ProblemDetail struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
	Title    *string `json:"title,omitempty"`
	Type     *string `json:"type,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	AvatarUrl     *string `json:"avatar_url,omitempty"`
	FirstName     *string `json:"first_name,omitempty"`
	LastName      *string `json:"last_name,omitempty"`
	MiddleInitial *string `json:"middle_initial,omitempty"`
	Phone         *string `json:"phone,omitempty"`
}

// User defines model for User.
type User struct {
	AvatarUrl     *string             `json:"avatar_url,omitempty"`
	CreatedAt     *time.Time          `json:"created_at,omitempty"`
	Email         openapi_types.Email `json:"email"`
	FirstName     string              `json:"first_name"`
	LastName      string              `json:"last_name"`
	MiddleInitial *string             `json:"middle_initial,omitempty"`
	Phone         *string             `json:"phone,omitempty"`
	UpdatedAt     *time.Time          `json:"updated_at,omitempty"`
	UserId        string              `json:"user_id"`
}

// UserExistsResponse defines model for UserExistsResponse.
type UserExistsResponse struct {
	// AuthMethods Empty array when exists is false
	AuthMethods []UserExistsResponseAuthMethods `json:"auth_methods"`
	Exists      bool                            `json:"exists"`
}

// UserExistsResponseAuthMethods defines model for UserExistsResponse.AuthMethods.
type UserExistsResponseAuthMethods string

// AddressID defines model for AddressID.
type AddressID = string

// CredentialID defines model for CredentialID.
type CredentialID = string

// PaymentID defines model for PaymentID.
type PaymentID = string

// UserID defines model for UserID.
type UserID = string

// BadRequest RFC 7807 Problem+JSON error body
type BadRequest = ProblemDetail

// Conflict RFC 7807 Problem+JSON error body
type Conflict = ProblemDetail

// Forbidden RFC 7807 Problem+JSON error body
type Forbidden = ProblemDetail

// NotFound RFC 7807 Problem+JSON error body
type NotFound = ProblemDetail

// Unauthorized RFC 7807 Problem+JSON error body
type Unauthorized = ProblemDetail

// serviceJWTContextKey is the context key for ServiceJWT security scheme
type serviceJWTContextKey string

// userJWTContextKey is the context key for UserJWT security scheme
type userJWTContextKey string

// GetUserCredentialsParams defines parameters for GetUserCredentials.
type GetUserCredentialsParams struct {
	// Email Email address to look up
	Email openapi_types.Email `form:"email" json:"email"`
}

// GetUserExistsParams defines parameters for GetUserExists.
type GetUserExistsParams struct {
	// Email Email address to check
	Email openapi_types.Email `form:"email" json:"email"`
}

// AddAddressJSONRequestBody defines body for AddAddress for application/json ContentType.
type AddAddressJSONRequestBody = AddressInput

// UpdateAddressJSONRequestBody defines body for UpdateAddress for application/json ContentType.
type UpdateAddressJSONRequestBody = AddressInput

// UpsertPaymentJSONRequestBody defines body for UpsertPayment for application/json ContentType.
type UpsertPaymentJSONRequestBody = PaymentMethodInput

// UpdatePreferencesJSONRequestBody defines body for UpdatePreferences for application/json ContentType.
type UpdatePreferencesJSONRequestBody = Preferences

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateUserRequest

// InternalCreateUserPasskeyJSONRequestBody defines body for InternalCreateUserPasskey for application/json ContentType.
type InternalCreateUserPasskeyJSONRequestBody = PasskeyCredential

// InternalUpdateUserPasskeyJSONRequestBody defines body for InternalUpdateUserPasskey for application/json ContentType.
type InternalUpdateUserPasskeyJSONRequestBody = PasskeyCredential
