// Code generated by MockGen. DO NOT EDIT.
// Source: banned.go
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../testutil/mocks/banned_checker.go -source=banned.go BannedChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBannedChecker is a mock of BannedChecker interface.
type MockBannedChecker struct {
	ctrl     *gomock.Controller
	recorder *MockBannedCheckerMockRecorder
	isgomock struct{}
}

// MockBannedCheckerMockRecorder is the mock recorder for MockBannedChecker.
type MockBannedCheckerMockRecorder struct {
	mock *MockBannedChecker
}

// NewMockBannedChecker creates a new mock instance.
func NewMockBannedChecker(ctrl *gomock.Controller) *MockBannedChecker {
	mock := &MockBannedChecker{ctrl: ctrl}
	mock.recorder = &MockBannedCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBannedChecker) EXPECT() *MockBannedCheckerMockRecorder {
	return m.recorder
}

// IsBanned mocks base method.
func (m *MockBannedChecker) IsBanned(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBanned", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBanned indicates an expected call of IsBanned.
func (mr *MockBannedCheckerMockRecorder) IsBanned(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBanned", reflect.TypeOf((*MockBannedChecker)(nil).IsBanned), ctx, email)
}
