// Code generated by MockGen. DO NOT EDIT.
// Source: komodo-auth-api/internal/db (interfaces: CacheClientCallers)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../testutil/mocks/cache_client_callers.go komodo-auth-api/internal/db CacheClientCallers
//

package mocks

import (
	context "context"
	db "komodo-auth-api/internal/db"
	reflect "reflect"
	time "time"

	webauthn "github.com/go-webauthn/webauthn/webauthn"
	gomock "go.uber.org/mock/gomock"
)

type MockCacheClientCallers struct {
	ctrl     *gomock.Controller
	recorder *MockCacheClientCallersMockRecorder
	isgomock struct{}
}

type MockCacheClientCallersMockRecorder struct {
	mock *MockCacheClientCallers
}

func NewMockCacheClientCallers(ctrl *gomock.Controller) *MockCacheClientCallers {
	mock := &MockCacheClientCallers{ctrl: ctrl}
	mock.recorder = &MockCacheClientCallersMockRecorder{mock}
	return mock
}

func (m *MockCacheClientCallers) EXPECT() *MockCacheClientCallersMockRecorder {
	return m.recorder
}

func (m *MockCacheClientCallers) DeleteOTPAttempts(ctx context.Context, email string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteOTPAttempts", ctx, email)
}

func (mr *MockCacheClientCallersMockRecorder) DeleteOTPAttempts(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOTPAttempts", reflect.TypeOf((*MockCacheClientCallers)(nil).DeleteOTPAttempts), ctx, email)
}

func (m *MockCacheClientCallers) DeleteWebAuthnLoginSession(ctx context.Context, challenge string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebAuthnLoginSession", ctx, challenge)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCacheClientCallersMockRecorder) DeleteWebAuthnLoginSession(ctx, challenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebAuthnLoginSession", reflect.TypeOf((*MockCacheClientCallers)(nil).DeleteWebAuthnLoginSession), ctx, challenge)
}

func (m *MockCacheClientCallers) DeleteWebAuthnRegistrationSession(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebAuthnRegistrationSession", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCacheClientCallersMockRecorder) DeleteWebAuthnRegistrationSession(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebAuthnRegistrationSession", reflect.TypeOf((*MockCacheClientCallers)(nil).DeleteWebAuthnRegistrationSession), ctx, userID)
}

func (m *MockCacheClientCallers) ClaimSession(ctx context.Context, sessionID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimSession", ctx, sessionID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCacheClientCallersMockRecorder) ClaimSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimSession", reflect.TypeOf((*MockCacheClientCallers)(nil).ClaimSession), ctx, sessionID)
}

func (m *MockCacheClientCallers) GenerateAndStoreOTP(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAndStoreOTP", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCacheClientCallersMockRecorder) GenerateAndStoreOTP(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAndStoreOTP", reflect.TypeOf((*MockCacheClientCallers)(nil).GenerateAndStoreOTP), ctx, email)
}

func (m *MockCacheClientCallers) GetOTPAttempts(ctx context.Context, email string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOTPAttempts", ctx, email)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCacheClientCallersMockRecorder) GetOTPAttempts(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOTPAttempts", reflect.TypeOf((*MockCacheClientCallers)(nil).GetOTPAttempts), ctx, email)
}

func (m *MockCacheClientCallers) GetWebAuthnLoginSession(ctx context.Context, challenge string) (*db.WebAuthnLoginSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebAuthnLoginSession", ctx, challenge)
	ret0, _ := ret[0].(*db.WebAuthnLoginSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCacheClientCallersMockRecorder) GetWebAuthnLoginSession(ctx, challenge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebAuthnLoginSession", reflect.TypeOf((*MockCacheClientCallers)(nil).GetWebAuthnLoginSession), ctx, challenge)
}

func (m *MockCacheClientCallers) GetWebAuthnRegistrationSession(ctx context.Context, userID string) (*webauthn.SessionData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebAuthnRegistrationSession", ctx, userID)
	ret0, _ := ret[0].(*webauthn.SessionData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCacheClientCallersMockRecorder) GetWebAuthnRegistrationSession(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebAuthnRegistrationSession", reflect.TypeOf((*MockCacheClientCallers)(nil).GetWebAuthnRegistrationSession), ctx, userID)
}

func (m *MockCacheClientCallers) IncrOTPAttempts(ctx context.Context, email string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrOTPAttempts", ctx, email)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCacheClientCallersMockRecorder) IncrOTPAttempts(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrOTPAttempts", reflect.TypeOf((*MockCacheClientCallers)(nil).IncrOTPAttempts), ctx, email)
}

func (m *MockCacheClientCallers) IsFamilyRevoked(ctx context.Context, familyID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFamilyRevoked", ctx, familyID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCacheClientCallersMockRecorder) IsFamilyRevoked(ctx, familyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFamilyRevoked", reflect.TypeOf((*MockCacheClientCallers)(nil).IsFamilyRevoked), ctx, familyID)
}

func (m *MockCacheClientCallers) IsRevoked(ctx context.Context, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRevoked", ctx, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCacheClientCallersMockRecorder) IsRevoked(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRevoked", reflect.TypeOf((*MockCacheClientCallers)(nil).IsRevoked), ctx, jti)
}

func (m *MockCacheClientCallers) Reachable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reachable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCacheClientCallersMockRecorder) Reachable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reachable", reflect.TypeOf((*MockCacheClientCallers)(nil).Reachable), ctx)
}

func (m *MockCacheClientCallers) StoreRevoked(ctx context.Context, jti string, remaining time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRevoked", ctx, jti, remaining)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCacheClientCallersMockRecorder) StoreRevoked(ctx, jti, remaining any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRevoked", reflect.TypeOf((*MockCacheClientCallers)(nil).StoreRevoked), ctx, jti, remaining)
}

func (m *MockCacheClientCallers) StoreRevokedFamily(ctx context.Context, familyID string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRevokedFamily", ctx, familyID, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCacheClientCallersMockRecorder) StoreRevokedFamily(ctx, familyID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRevokedFamily", reflect.TypeOf((*MockCacheClientCallers)(nil).StoreRevokedFamily), ctx, familyID, ttl)
}

func (m *MockCacheClientCallers) StoreWebAuthnLoginSession(ctx context.Context, challenge string, session *db.WebAuthnLoginSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWebAuthnLoginSession", ctx, challenge, session)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCacheClientCallersMockRecorder) StoreWebAuthnLoginSession(ctx, challenge, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWebAuthnLoginSession", reflect.TypeOf((*MockCacheClientCallers)(nil).StoreWebAuthnLoginSession), ctx, challenge, session)
}

func (m *MockCacheClientCallers) StoreWebAuthnRegistrationSession(ctx context.Context, userID string, session *webauthn.SessionData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreWebAuthnRegistrationSession", ctx, userID, session)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCacheClientCallersMockRecorder) StoreWebAuthnRegistrationSession(ctx, userID, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreWebAuthnRegistrationSession", reflect.TypeOf((*MockCacheClientCallers)(nil).StoreWebAuthnRegistrationSession), ctx, userID, session)
}

func (m *MockCacheClientCallers) VerifyOTP(ctx context.Context, email, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyOTP", ctx, email, code)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCacheClientCallersMockRecorder) VerifyOTP(ctx, email, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyOTP", reflect.TypeOf((*MockCacheClientCallers)(nil).VerifyOTP), ctx, email, code)
}
