// Code generated by MockGen. DO NOT EDIT.
// Source: komodo-auth-api/internal/clients (interfaces: HttpClientCallers)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../testutil/mocks/http_client_callers.go komodo-auth-api/internal/clients HttpClientCallers
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	clients "komodo-auth-api/internal/clients"
	comms "komodo-auth-api/internal/models/comms"
	user "komodo-auth-api/internal/models/user"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHttpClientCallers is a mock of HttpClientCallers interface.
type MockHttpClientCallers struct {
	ctrl     *gomock.Controller
	recorder *MockHttpClientCallersMockRecorder
	isgomock struct{}
}

// MockHttpClientCallersMockRecorder is the mock recorder for MockHttpClientCallers.
type MockHttpClientCallersMockRecorder struct {
	mock *MockHttpClientCallers
}

// NewMockHttpClientCallers creates a new mock instance.
func NewMockHttpClientCallers(ctrl *gomock.Controller) *MockHttpClientCallers {
	mock := &MockHttpClientCallers{ctrl: ctrl}
	mock.recorder = &MockHttpClientCallersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpClientCallers) EXPECT() *MockHttpClientCallersMockRecorder {
	return m.recorder
}

// CreatePasskeyCredential mocks base method.
func (m *MockHttpClientCallers) CreatePasskeyCredential(ctx context.Context, userID, bearerToken string, cred clients.PasskeyCredentialDescriptor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePasskeyCredential", ctx, userID, bearerToken, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePasskeyCredential indicates an expected call of CreatePasskeyCredential.
func (mr *MockHttpClientCallersMockRecorder) CreatePasskeyCredential(ctx, userID, bearerToken, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePasskeyCredential", reflect.TypeOf((*MockHttpClientCallers)(nil).CreatePasskeyCredential), ctx, userID, bearerToken, cred)
}

// GetUserByID mocks base method.
func (m *MockHttpClientCallers) GetUserByID(ctx context.Context, userID, bearerToken string) (*user.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID, bearerToken)
	ret0, _ := ret[0].(*user.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockHttpClientCallersMockRecorder) GetUserByID(ctx, userID, bearerToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockHttpClientCallers)(nil).GetUserByID), ctx, userID, bearerToken)
}

// GetUserCredentials mocks base method.
func (m *MockHttpClientCallers) GetUserCredentials(ctx context.Context, email, bearerToken string) (*user.CredentialsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCredentials", ctx, email, bearerToken)
	ret0, _ := ret[0].(*user.CredentialsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCredentials indicates an expected call of GetUserCredentials.
func (mr *MockHttpClientCallersMockRecorder) GetUserCredentials(ctx, email, bearerToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCredentials", reflect.TypeOf((*MockHttpClientCallers)(nil).GetUserCredentials), ctx, email, bearerToken)
}

// ListPasskeyCredentials mocks base method.
func (m *MockHttpClientCallers) ListPasskeyCredentials(ctx context.Context, userID, bearerToken string) ([]clients.PasskeyCredentialDescriptor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPasskeyCredentials", ctx, userID, bearerToken)
	ret0, _ := ret[0].([]clients.PasskeyCredentialDescriptor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPasskeyCredentials indicates an expected call of ListPasskeyCredentials.
func (mr *MockHttpClientCallersMockRecorder) ListPasskeyCredentials(ctx, userID, bearerToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPasskeyCredentials", reflect.TypeOf((*MockHttpClientCallers)(nil).ListPasskeyCredentials), ctx, userID, bearerToken)
}

// SendEmail mocks base method.
func (m *MockHttpClientCallers) SendEmail(ctx context.Context, body comms.SendEmailJSONRequestBody) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", ctx, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockHttpClientCallersMockRecorder) SendEmail(ctx, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockHttpClientCallers)(nil).SendEmail), ctx, body)
}

// UpdatePasskeyCredential mocks base method.
func (m *MockHttpClientCallers) UpdatePasskeyCredential(ctx context.Context, userID, bearerToken string, cred clients.PasskeyCredentialDescriptor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasskeyCredential", ctx, userID, bearerToken, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasskeyCredential indicates an expected call of UpdatePasskeyCredential.
func (mr *MockHttpClientCallersMockRecorder) UpdatePasskeyCredential(ctx, userID, bearerToken, cred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasskeyCredential", reflect.TypeOf((*MockHttpClientCallers)(nil).UpdatePasskeyCredential), ctx, userID, bearerToken, cred)
}
