// Code generated by MockGen. DO NOT EDIT.
// Source: komodo-auth-api/internal/api (interfaces: TokenAuthority)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../testutil/mocks/token_authority.go komodo-auth-api/internal/api TokenAuthority
//

// Package mocks is a generated GoMock package.
package mocks

import (
	jwt "komodo-auth-api/internal/jwt"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenAuthority is a mock of TokenAuthority interface.
type MockTokenAuthority struct {
	ctrl     *gomock.Controller
	recorder *MockTokenAuthorityMockRecorder
	isgomock struct{}
}

// MockTokenAuthorityMockRecorder is the mock recorder for MockTokenAuthority.
type MockTokenAuthorityMockRecorder struct {
	mock *MockTokenAuthority
}

// NewMockTokenAuthority creates a new mock instance.
func NewMockTokenAuthority(ctrl *gomock.Controller) *MockTokenAuthority {
	mock := &MockTokenAuthority{ctrl: ctrl}
	mock.recorder = &MockTokenAuthorityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenAuthority) EXPECT() *MockTokenAuthorityMockRecorder {
	return m.recorder
}

// ParseClaims mocks base method.
func (m *MockTokenAuthority) ParseClaims(token string) (*jwt.CustomClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseClaims", token)
	ret0, _ := ret[0].(*jwt.CustomClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseClaims indicates an expected call of ParseClaims.
func (mr *MockTokenAuthorityMockRecorder) ParseClaims(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseClaims", reflect.TypeOf((*MockTokenAuthority)(nil).ParseClaims), token)
}

// SignToken mocks base method.
func (m *MockTokenAuthority) SignToken(issuer, subject, audience string, ttl int64, scopes []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignToken", issuer, subject, audience, ttl, scopes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignToken indicates an expected call of SignToken.
func (mr *MockTokenAuthorityMockRecorder) SignToken(issuer, subject, audience, ttl, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignToken", reflect.TypeOf((*MockTokenAuthority)(nil).SignToken), issuer, subject, audience, ttl, scopes)
}

func (m *MockTokenAuthority) SignTokenWithAZP(issuer, subject, audience, azp string, ttl int64, scopes []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignTokenWithAZP", issuer, subject, audience, azp, ttl, scopes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTokenAuthorityMockRecorder) SignTokenWithAZP(issuer, subject, audience, azp, ttl, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignTokenWithAZP", reflect.TypeOf((*MockTokenAuthority)(nil).SignTokenWithAZP), issuer, subject, audience, azp, ttl, scopes)
}

func (m *MockTokenAuthority) SignRefreshToken(issuer, subject, audience, azp, familyID string, ttl int64, scopes []string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignRefreshToken", issuer, subject, audience, azp, familyID, ttl, scopes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockTokenAuthorityMockRecorder) SignRefreshToken(issuer, subject, audience, azp, familyID, ttl, scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignRefreshToken", reflect.TypeOf((*MockTokenAuthority)(nil).SignRefreshToken), issuer, subject, audience, azp, familyID, ttl, scopes)
}

// ValidateAndParseClaims mocks base method.
func (m *MockTokenAuthority) ValidateAndParseClaims(token string) (*jwt.CustomClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAndParseClaims", token)
	ret0, _ := ret[0].(*jwt.CustomClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateAndParseClaims indicates an expected call of ValidateAndParseClaims.
func (mr *MockTokenAuthorityMockRecorder) ValidateAndParseClaims(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAndParseClaims", reflect.TypeOf((*MockTokenAuthority)(nil).ValidateAndParseClaims), token)
}

// VerificationKeys mocks base method.
func (m *MockTokenAuthority) VerificationKeys() []jwt.VerificationKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerificationKeys")
	ret0, _ := ret[0].([]jwt.VerificationKey)
	return ret0
}

// VerificationKeys indicates an expected call of VerificationKeys.
func (mr *MockTokenAuthorityMockRecorder) VerificationKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerificationKeys", reflect.TypeOf((*MockTokenAuthority)(nil).VerificationKeys))
}
