import * as cdk from 'aws-cdk-lib';
import type { EnvConfig } from 'komodo-forge-sdk-ts/cdk/config';
export declare const API_NAME = "komodo-auth-api";
export declare const PUBLIC_PORT = 7011;
export declare const PRIVATE_PORT = 7012;
export declare const DEV_CONFIG: EnvConfig;
export declare const STG_CONFIG: EnvConfig;
export declare const PROD_CONFIG: EnvConfig;
export declare const buildStack: (stack: cdk.Stack, cfg: EnvConfig) => void;
export declare const createInfra: () => void;
